scale_factors = [1.3, 1.2, 1.1, 0.9, 0.8, 0.7]
cop_reduction = 0.45

[variable]
application_number = "신청번호"
u_wall             = "외벽 평균 열관류율"
u_roof             = "지붕 평균 열관류율"
u_floor            = "바닥 평균 열관류율_직접"
u_window           = "창호 평균 열관류율"
shgc               = "SHGC 평균"
boiler_space       = "온열설비 효율_보일러"
ehp_heating        = "온열설비 효율_히트펌프 전기"
ghp_heating        = "온열설비 효율_히트펌프 가스"
ehp_cooling        = "냉열설비 효율_압축식"
ghp_cooling        = "냉열설비 효율_압축식(LNG)"
absorption         = "냉열설비 효율_흡수식(없음)"
boiler_water       = "급탕설비 효율_보일러"
light_density      = "평균 조명밀도"
recovery_heating   = "평균열회수율_전열교환기"
recovery_colling   = "평균열회수율냉_전열교환기"
